#pragma once

const float MENU_OPTION_WIDTH = 250;
const float MENU_OPTION_HEIGHT = 80;

const sf::Color BG_COLOR(50, 50, 50);
const sf::Color RECT_COLOR(206, 216, 229);
const sf::Color ACTIVE_RECT_COLOR(236, 246, 255);
const sf::Vector2f RECT_SIZE(MENU_OPTION_WIDTH, MENU_OPTION_HEIGHT);

const int CELL_LENGTH = 75;
const int BOARD_SIZE = 8;

const int PAWN_SCORE = 1;
const int KNIGHT_SCORE = 3;
const int BISHOP_SCORE = 3;
const int ROOK_SCORE = 5;
const int QUEEN_SCORE = 9;

enum class PIECES {
	WHITE_PAWN,
	WHITE_ROOK,
	WHITE_BISHOP,
	WHITE_KING,
	WHITE_QUEEN,
	WHITE_KNIGHT,

	BLACK_PAWN,
	BLACK_ROOK,
	BLACK_BISHOP,
	BLACK_KING,
	BLACK_QUEEN,
	BLACK_KNIGHT,

	TILE_SET,
	BACKGROUND,

	N_TEXTURES
};
